/// Flutter icons QabussIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QabussIcons
///      fonts:
///       - asset: fonts/QabussIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QabussIcons {
  QabussIcons._();

  static const _kFontFam = 'QabussIcons';

  static const IconData articles = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bank = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData beauty_cosmetics = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cafe_coffee_shop = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData car_wheel = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData clinics = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cocktail = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData cupcake = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData dumbbell = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData events = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData explore_filled = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData fashion = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData flower = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData museum = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData nearby = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData puzzle = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData salons_spas = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData siren = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData skyline = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData sunglasses = const IconData(0xe815, fontFamily: _kFontFam);
}
